Repository bicycle-innovation-lab/admin-app, pull requests merged in 2019-05, with the labels that each got.

#6 Feature seperate login page
  package-lock.json
  src/App.vue
  src/pages/PageMain.vue
  src/router.js
Labels: enhancement

#8 Feature user display
  package.json
  src/components/Navigation.vue
  src/components/UserDisplay.vue
  src/store/modules/auth.js
  src/store/modules/user.js
Labels: enhancement, good first issue, help wanted

#20 Feature create user component
  src/components/CreateUser.vue
  src/pages/PageHome.vue
  src/pages/PageUser.vue
  src/store/modules/user.js
Labels: enhancement

#25 Feature dynamic toolbar title
  src/components/Navigation.vue
  src/pages/PageBookings.vue
  src/pages/PageHome.vue
  src/pages/PageMain.vue
  src/pages/PageProjects.vue
  src/pages/PageUser.vue
  src/router.js
  src/store/modules/ui.js
  src/store/store.js
Labels: enhancement

#24 After refresh, set axios.headers and getCurrentUser again
  src/services/api.service.js
  src/services/auth.service.js
  src/store/modules/auth.js
  src/store/modules/user.js
Labels: help wanted

#19 Feature data table
  src/components/DataTable.vue
  src/pages/PageBikes.vue
Labels: enhancement
